github/freno

resources/pt-archiver/FrenoThrottler.pm
This minor syntax change makes the throttler plugin work on older Perl versions, such as `5.14.*`
=> pt-archiver plugin perl change to be compatible with older perl

doc/http.md, go/base/recent_app.go, go/group/consensus_service.go, go/group/store.go, go/http/api.go, go/throttle/check.go, go/throttle/throttler.go
This PR tracks down recent apps:
- which app made checks recently?
- from what remote address?
This, in addition to the `/recent-apps` API, will give us better visibility (on top of existing metrics) into what's hitting `freno`.
=> Tracking recent apps usage

doc/mysql.md, go/base/throttle_metric.go, go/config/mysql_config.go, go/group/fsm.go, go/mysql/mysql_inventory.go, go/mysql/probe.go, go/throttle/check.go, go/throttle/mysql.go, go/throttle/mysql_test.go, go/throttle/throttler.go, go/throttle/throttler_test.go
Storyline: https://github.com/github/freno/issues/29
This PR adds the `IgnoreHostsCount` config (in both general-MySQL scope as well as specific MySQL cluster scope).
With this setting (default `0`), up to `n` hosts can be safely ignored while aggregating metrics. Say `IgnoreHostsCount` is set to `1`. Then in a cluster, `1` host may be down, or return an error. Or `1` host may exceed threshold -- and will be ignored. 
If all other hosts are good and with values < threshold, then `freno` is happy to ignore those `n` hosts.
=> support for IgnoreHostsCount config

doc/http.md, doc/mysql.md, go/http/api.go, go/throttle/check.go
A new API endpoint, `/check-read/<app>/<store-type>/<store-name>/<threshold>`, allows one to test the current store's value with a user-given threshold, overriding the configured threshold.
This read-check _should not be used to approve writes_. Writes should only be approved by using the `/check` request.
However this check is known to be useful, at least in one common scenario: a monitoring of a MySQL cluster based on replication lag. In such case, we may have write requests followed by read requests. We may happen to know the elapsed time between write & read. As an example, say `2.5s` have passed between the write and read. The check `/check-read/archive/mysql/main1/2.5` confirms or denies that relevant replicas are up-to-date for the `2.5s` elapsed time. We can therefore read from …
=> supporting /check-read with user provided threshold

go/base/metric_health.go, go/http/api.go, go/throttle/check.go, go/throttle/throttler.go
This PR takes advantage of the fact `freno` runs self-checks via the special `freno` app name, iterating on all aggregated metrics.
It marks the last-known-time where a metric was checked to be "OK".
With this PR we generate metrics (i.e. a _gauge_) that tells the elapsed seconds since a given metric was "OK".
This is useful for setting up alerts on a metric that hasn't been OK in a long time.
=> producing metrics for time-since-metric-check-was-ok

go/config/config.go, go/throttle/throttler.go, vendor/github.com/bradfitz/gomemcache/LICENSE, vendor/github.com/bradfitz/gomemcache/README.md, vendor/github.com/bradfitz/gomemcache/memcache/memcache.go, vendor/github.com/bradfitz/gomemcache/memcache/memcache_test.go, vendor/github.com/bradfitz/gomemcache/memcache/selector.go, vendor/github.com/bradfitz/gomemcache/memcache/selector_test.go
This PR introduces the `MemcacheServers` config. When provided, `freno` writes aggregated metrics to `memcache`.
Aggregated values are for example the replication lag on `mysql/my_main_cluster`.
Aggregated values are written to `memcache` as soon as they are calculated, and asynchronously from the main thread. ~~The values are written as strings, but are in fact floating point numbers.~~
~~An invalid value (error on aggregating) is the empty string.~~
**Edit**
Upon invalid read `freno` removes the entry from `memcache`
See value format updates in https://github.com/github/freno/pull/46#issuecomment-308325400
It is not `freno`'s responsibility to invalidate the `memcache` entries, though it sets a `1` second expiration (the minimal value it can use)
Memcache client is …
=> Per config, freno writes aggregated metrics to memcache

go/throttle/throttler.go
- Remove variable definition on the method from the method signature.
- have the Metric getters more consistent code-wise
The changes here are no big deal. Just was reading the code and found more fluent to have it like that. Not sure what you think about it.
=> small code refactor

go/mysql/probe.go
This PR sets `interpolateParams=true` on the MySQL client connection, which disables prepared statements (interpolation happens on client).
This saves round trips to MySQL per query and should otherwise not affect behavior.
cc @miguelff
=> Avoiding prepared statements

doc/clients.md, doc/memcache.md, go/config/config.go, go/throttle/throttler.go, resources/freno.conf.sample.json
Followup on https://github.com/github/freno/pull/46:
- Adding `MemcachePath` config variable, defaulting `"freno"` as memcache key prefix
- Added memcache documentation.
=> support MemcachePath, key prefix ; added memcache documentation

build.sh, doc/high-availability.md, resources/freno.conf.sample.json, resources/freno.conf.skeleton.json
This PR adds a `build` script that created `.deb` and `.rpm` packaged for widespread distribution. Such binaries will be included on the `releases` page.
As example, the `.deb` package file includes:
```
drwxr-xr-x 0/0               0 2017-10-09 05:34 ./
drwxr-xr-x 0/0               0 2017-10-09 05:34 ./etc/
drwxr-xr-x 0/0               0 2017-10-09 05:34 ./etc/init.d/
-rwxr-xr-x 0/0            1464 2017-10-09 05:34 ./etc/init.d/freno
-rw-r--r-- 0/0             286 2017-10-09 05:34 ./etc/freno.conf.json
drwxr-xr-x 0/0               0 2017-10-09 05:34 ./usr/
drwxr-xr-x 0/0               0 2017-10-09 05:34 ./usr/bin/
-rwxr-xr-x 0/0        11582053 2017-10-09 05:34 ./usr/bin/freno
drwxr-xr-x 0/0               0 2017-10-09 05:34 ./usr/share/
drwxr-xr-x 0/0               0 2017-10-09 05:34 …
```
=> Binary packaging

.travis.yml, build.sh, script/ensure-go-installed
While still allowing `1.8`, we are moving towards `1.9`. I'd in particular like to use [Test Helper functions](https://golang.org/doc/go1.9#test-helper).
=> Build using and requires go1.9

go/group/raft.go
`raft.is_healthy` will be advertised in `/debug/metrics`
`raft.is_healthy` is `true` when the node is either the `Leader` or a `Follower`.
=> adding raft.is_healthy metric

go/throttle/check.go
Local checks running at `5s` intervals are at very low resolution. Local checks are susceptible to failure when an aggressive operation is running. With such low resolution of `5s` it is plausible that multiple successive self checks in a row will all fail.
This PR reduces interval to `500ms`, which reduces the probability for health check failure.
=> More frequent local checks

go/group/raft.go
In this PR the leader check does not run a synchronous operation, but relies on the `State` variables (same thing done with `orchestrator`).
=> Simpler and more lightweight leader check

doc/mysql.md, go/config/mysql_config.go, go/mysql/mysql_throttle_metric.go, go/mysql/probe.go, go/throttle/throttler.go
Supporting `CacheMillis` in configuration, e.g.:
```
"Clusters": {
"local": {
"MetricQuery": "select rand()*1000",
"CacheMillis": 5000,
}
}
```
`CacheMillis` is supported in global `MySQL` config or in per-cluster config.
MySQL metrics are being polled every `100ms` (potentially we will drop down to a `50ms` interval).
For some queries it makes absolute sense to run at that interval ; for others it doesn't.
`CacheMillis` will make probing cache the result for designated time (`0` == no cache). With `CacheMillis > 0` the backend MySQL servers will see less queries. `freno` will continue to run the probes, internally, at `100ms` interval, but most of these will hit the internal cache and never reach MySQL.
An example of such metric that doesn't make sense to run 10 times per sec: reading …
=> support for CacheMillis: caching of metric result

go/http/api.go
This PR adds a new type of check: `/check-if-exists/:app/:storeType/:storeName`
The API is identical to the `/check` test, except this check supports _optional metrics_. If the metric exists, then a threshold check is made as usual. But if the metric does not exist, the check returns with HTTP OK (200).
This is useful where we may have special tests for particular clusters. For example, all tests throttle on replication lag, and some other tests can throttle on master metrics, if such metrics are being collected and monitored by `freno`.
=> API: check-if-exists: return OK if metric does not exist

go/haproxy/parser.go
`freno` supports the `no check` status in `haproxy` as a valid indicator for a backend server.
=> support for 'no check'

doc/mysql.md, go/config/mysql_config.go, go/mysql/mysql_http_check.go, go/mysql/mysql_inventory.go, go/mysql/probe.go, go/throttle/mysql.go, go/throttle/mysql_test.go, go/throttle/throttler.go
In this PR `freno` is capable of running `HTTP` checks on MySQL nodes. This is similarly to how `HAProxy` runs checks, and in fact intends to replace HAProxy's checks (the original reason: HAProxy's inability to transition `DOWN`->`NOLB`, something we find very important).
=> HTTP checks for MySQL

doc/mysql.md, go/config/mysql_config.go, go/config/vitess_config.go, go/throttle/throttler.go, go/vitess/api_client.go
This PR supports extracting list of hosts from Vitess's `vtctld` API.
It uses a `api/ks_tablets` endpoint, which is not (yet?) present in upstream. It supports specifying a shard, if desired, or it supports not specifying a shard, in which case all shards are considered.
=> Getting hosts from vitess API

doc/mysql.md, go/config/mysql_config.go, go/throttle/throttler.go
A new config, `IgnoreHosts` is introduced. Example:
```json
"MySQL": {
"ThrottleThreshold": 1,
"IgnoreHosts": [
"127.0.0.5"
],
"Clusters": {
"local": {
"User": "msandbox",
"Password": "msandbox",
"CacheMillis": 5000,
"ThrottleThreshold": 800,
"IgnoreHosts": [
"127.0.0.2"
],
"StaticHostsSettings" : {
"Hosts": [
"127.0.0.2:5555",
"127.0.0.1:20192",
"127.0.0.1:20193",
"127.0.0.1:20194"
]
}
}
}
```
As shown in the above, `IgnoreHosts` can appear in `MySQL` scope, or can appear (and override) in per-cluster scope, similarly to other metrics.
`IgnoreHosts` is an array of strings; a `freno` ignores a host if the hostname has a substring found in `IgnoreHosts`. e.g., in the above `"0.0.2:"` would disable the host `"127.0.0.2:5555"`
=> Support for IgnoreHosts config

go/http/api.go
on error, `aggregated-metrics` output discards numeric value, and indicates `error:`.
Also, it supports the `?brief=true` query param which uses 3 digit precision for floating point values.
=> change of aggregated-metrics format on error

doc/mysql.md, go/config/mysql_config.go, go/mysql/mysql_inventory.go, go/mysql/probe.go, go/throttle/mysql.go, go/throttle/mysql_test.go, go/throttle/throttler.go
`IgnoreHostsThreshold`: applies a conditional to the `IgnoreHostsCount` logic: for hosts with errors, no conditional applies. For hosts reporting a value, the value needs to be _higher_ than given threshold to be ignored.
A use case: ignore up to `n` lagging replicas, on condition that they're lagging _at least_ `10.0sec`.
In this use case, we may expect that hosts lagging over `10.0sec` are auto-evicted from read-pool by a proxy.
=> Introducing `IgnoreHostsThreshold` config variable

go/base/throttle_metric.go, go/config/mysql_config.go, go/throttle/mysql.go, go/throttle/mysql_test.go, go/throttle/throttler.go
When this new `MySQL`-scope config `"IgnoreDialTcpErros": true`, `freno` will silently ignore (skip) hosts which is failed to connect via TCP dial error.
The idea is that `freno` would only consider hosts which it is able to reach.
As with other skips/ignores, if `freno` exhausts the entire roster and is left with no actual hosts that it can probe, it returns an error. So, for example, a `api/check/me/mysql/mysqlcluster1` will skip all hosts that are DOWN, and return the max lag of the remaining hosts. If all hosts are down, that's an error.
=> Support IgnoreDialTcpErros config

go/config/mysql_config.go, go/throttle/throttler.go
As per https://github.com/github/freno/pull/78#discussion_r249034696, this PR fixes config typo from `IgnoreDialTcpErros` to `IgnoreDialTcpErrors`.
cc @mrluanma
=> Fixed IgnoreDialTcpErrors typo

go/mysql/mysql_inventory.go, go/mysql/mysql_throttle_metric.go, go/throttle/mysql.go, go/throttle/mysql_test.go, go/throttle/throttler.go
Fixes https://github.com/github/freno/issues/87
`freno` should store MySQL metric results in cluster-ware context. Today the metrics are stored based on `InstanceKey`: hostname+port.
But it is possible for same instance to participate in multiple pools, which have different metrics. Thus, a "cluster" context is now added.
=> collected metrics are cluster-aware

go/cmd/freno/main.go, go/config/config.go, go/group/consensus.go, go/group/consensus_service.go, go/group/mysql.go, go/group/raft.go, go/group/store.go, go/http/api.go, go/throttle/throttler.go
This PR offers statefulness and leadership via shared MySQL backend, as an alternative to the raft setup.
Some notes:
- Either `raft` or `mysql` are used. Provide one of:
- `RaftDataDir`
- `BackendMySQLHost`
there is no seamless transition of data between the two.
If both are defined: WIP
- This adds dependency on a MySQL backend
- The number of `freno` services can now be arbitrary. Raft requires 3 or more, but not much more. With MySQL backend 2 is also good.
- This simplifies deployments on `k8s` 
- `freno` only accesses a MySQL master and does not read from replicas. The load is places is very low.
- With `Datacenter` and `Environment` configuration variables, `freno` builds a "domain". Multiple `freno` clusters can all use same MySQL backend, if on different DCs or environments. …
=> MySQL backend as alternative to raft quorum

doc/high-availability.md, doc/mysql-backend.md, doc/raft.md, go/cmd/freno/main.go, go/group/consensus.go, go/group/mysql.go, go/group/store.go
Followup to https://github.com/github/freno/pull/89
In this PR:
- When both MySQL and raft are configured (both `RaftDataDir` and `BackendMySQLHost` are non-empty), consensus is made by MySQL as opposed to Raft.
- Add documentation for MySQL backend
=> MySQL backend takes higher priority than raft consensus

go/config/config.go, go/config/haproxy_config.go, go/config/haproxy_config_test.go, go/config/mysql_config.go, go/group/mysql.go, go/haproxy/parser.go, go/throttle/throttler.go
HAProxy settings now support multiple HAProxy addresses.
One may either provide e.g.
```json
"HAProxySettings": {
"Host": "10.0.0.1",
"Port": 1010,
"PoolName": "ro_pool"
}
```
or:
```
"HAProxySettings": {
"Addresses": "10.0.0.1:1010,20.0.0.2:2020,30.0.0.3:3030",
"PoolName": "ro_pool"
}
```
If multiple addresses are provided, `freno` appends the roster lists from all. It will not check for duplicates.
=> HAProxy settings: support 'Addresses', multi-address value

go/group/mysql.go
The MySQL backend setup will now use `hostname:port` as the service ID, as opposed to just `hostname`.
This will be used in a future iteration where nodes in the same group could contact domain leaders using `hostname:port`.
=> MySQL service ID: include port number

go/haproxy/host.go, go/haproxy/parser.go, go/haproxy/parser_test.go, go/haproxy/throttle.go, go/throttle/throttler.go
a more thorough parsing of the HAProxy status page: return not only the hosts relevant to `freno`, but also the complete list of backend hosts with their status.
=> More complete parsing of HAProxy status

go/group/mysql.go, go/throttle/throttler.go
When using MySQL backend, Every `10sec` reload/refresh throttled-apps based on backend table content. This is as opposed to only re-reading when becoming leader.
This is important when using share-domain functionality, where multiple independent clusters share the same data. Leader of one cluster can update the data, and leaders in other clusters need to make sure to re-read it.
=> auto-refresh of MySQL backend throttled_apps

go/http/api.go
Adding the general purpose:
- `/consensus/leader`: identify of the leader service, be it via `raft` or MySQL backend.
- `/consensus/state`: consensus state (leader/follower/candidate), be it via `raft` or MySQL backend.
Which should be used in place of `/raft/leader` and `/raft/state`.
=> API: /consensus/leader and /consensus/state

go/group/mysql.go, go/throttle/check.go
This PR dark ships share domain checks.
A new internal check is introduced, named `freno-share-domain`. This check is the only one to actually utilize share-domain functionality, hence the only one which uses share-domain clusters health metrics when evaluating a check response.
As with any check, it generates its own metrics. We will evaluate use and future development of the functionality based on behavior of this metric (compare `freno-share-domain` with `freno`).
=> share domain checks dark shipping

go/cmd/freno/main.go, go/throttle/check.go, go/throttle/throttler.go
- share-domain: check `SecondsSinceHealth` as integer, fail when >= 1 (threshold is irrelevant)
- force-leadership: fixed parsing of command line argument
=> share domain; force-leadership fixes

go/throttle/throttler.go
This reduces MySQL polling interval from `100ms` per MySQL host to `50ms`. Thus, `freno` will visit every MySQL server up to 20 times per sec.
Aggregation interval is similarly reduced from `50ms` to `25ms`.
This is probably as low as we will go.
=> MySQL polling interval set to 50ms

go/http/api.go, go/throttle/check.go
Adding `check.low_priority.*` metrics, used specifically when `?p=low` requests are met.
Also, do not consider a throttled `read-check` for low-priority requests rejection.
=> explicit metrics for low-priority checks

go/cmd/freno/main.go, go/group/consensus_service.go, go/group/mysql.go, go/group/store.go, go/http/api.go, go/throttle/throttler.go
`consensus/status` returns a detailed JSON describing:
```
ServiceID                 string
Healthy                   bool
IsLeader                  bool
Leader                    string
State                     string
Domain                    string
ShareDomain               string
ShareDomainServices       map[string]string
ShareDomainServicesList   []string
HealthyDomainServicesList []string
```
This gives enough details for various purposes: identifying all active services within a domain, identifying which servers are collaborating on share-domain, which is healthy, which is leader etc.
A new table is created: 
```sql
CREATE TABLE service_health (
service_id varchar(128) NOT NULL,
domain varchar(32) NOT NULL,
share_domain varchar(32) NOT NULL,
last_seen_active timestamp NOT NULL …
```
=> Adding `consesus/status` API endpoint

.travis.yml, build.sh, go/base/http.go, go/throttle/throttler.go, script/ensure-go-installed
Starting this PR golang1.12 is required.
Feature-wise there's nothing specific to golang1.12; however, we wish to enforce some reasonable baseline.
Also, golang1.12 introduces somewhat different formatting conventions, and since those are tested as part of CI, we will require all future code to adhere to that formatting, i.e. all local builds will require go1.12.
=> Required: golang 1.12 or above

go/throttle/check.go
https://github.com/github/freno/pull/99 introduced share-domain based throttling, but dark-shipped the functionality to only apply to the share-domain internal app: https://github.com/github/freno/pull/99/files#diff-11634637460cb749624d521c95a9eaeeR79-R80
This PR brings the functionality to light. `freno` clusters sharing the same domain will cooperate such that lag in one freno cluster will cause throttling in all.
=> Throttling based on share-domain; un-darkship functionality

go/config/haproxy_config.go, go/config/haproxy_config_test.go, go/haproxy/parser.go, go/haproxy/parser_test.go, go/throttle/throttler.go
Up till now, `HAProxyConfigurationSettings.Addresses` could only contains `host:port[,host:port...]`
From now on, it may contain full blown URLs; for example, the following is valid:
```json
"Addresses": "https://some.host.name:1234/stats/pool/,10.0.0.2:1234"
```
In the above, `10.0.0.2:1234` is implicitly assumed to mean `http://10.0.0.2:1234`, and `https://some.host.name:1234/stats/pool/` is accepted and used "as-is".
=> HAProxyConfigurationSettings.Addresses may contain full URLs

doc/http.md, go/http/api.go
Support `check-read-if-exists`, which, similarly to `check-if-exists`, attempts a `read-check`.
- If the metric is known, `freno` checks for given threshold
- If the metric is unknown, freno returns `200 OK`
=> api: check-read-if-exists

.gitignore, go/config/haproxy_config.go, go/config/haproxy_config_test.go
This PR fixes the HAProxy address parse to correctly handle addresses without an explicit port:
Example: `http://123.123.123.123/haproxy_stats/`
=> Fix HAProxy address parse

go.mod, go.sum, pkg/throttle/throttler.go, pkg/vitess/api_client.go, pkg/vitess/api_client_test.go
This PR updates the Vitesssupport to only consider `REPLICA` tablet types for probing
Today this logic gathers any host available, including nodes that probably shouldn't get checked like `MASTER`, `DRAINED`, `SPARE`, `BACKUP`, `RESTORE`, etc. It can be valid for non-`REPLICA`s to have lag
The full list of tablet types available is here: https://godoc.org/vitess.io/vitess/go/vt/proto/topodata#TabletType
The `REPLICA` tablet-type is described as:
> REPLICA is a slave type. It is used to serve live traffic. A REPLICA can be promoted to MASTER. A demoted MASTER will go to REPLICA.
EDIT: `go mod` is pulling in a v.2.1.1 version of the Vitess package I used, due to this issue here: https://github.com/vitessio/vitess/issues/5019. I only use 1 x API struct so I think it's ok
=> Gather REPLICA tablet types from Vitess only

pkg/config/mysql_config.go, pkg/config/vitess_config.go, pkg/throttle/throttler.go, pkg/vitess/api_client.go, pkg/vitess/api_client_test.go
This PR adds support for polling MySQL replicas from a specific [Vitess "cell"](https://vitess.io/docs/concepts/cell/)
This change is backwards compatible with the current logic that fetches replicas from any Vitess cell. This change resolves duplicated Freno probing when Freno is deployed with a share domain and many Vitess cells
=> Support polling specific Vitess cells

pkg/vitess/api_client.go, pkg/vitess/api_client_test.go
This PR fixes a strange error when a Vitess API returns a `404 Not Found` for a missing keyspace:
```
2020-07-22 13:34:06 ERROR Unable to get vitess hosts from https://<hostname>/api, <keyspace>/: invalid character 'p' after top-level value
```
Now the HTTP status line is returned as an error unless a `200 OK` is returned
=> Vitess: handle non-200 HTTP status in ParseTablets()

build.sh
This PR updates `build.sh` for the path changes made in https://github.com/github/freno/pull/117
Specifically `go/` was renamed to `pkg/` and `go/cmd/freno/main.go` became `cmd/freno/main.go`
Today `build.sh` errors with:
```
tim@Tims-MacBook-Pro freno % bash build.sh                                        
stat go/: no such file or directory
```
=> Update build.sh for new code dirs

.travis.yml
This PR restores `.travis.yml` that was dropped in https://github.com/github/freno/pull/127
This is still needed for the build health badge
=> Restore .travis.yml

Dockerfile
This PR adds a Dockerfile that creates a Docker image of Freno
Alpine linux and a 2-stage build is used to make the image very small (< 20mb)
=> Add Dockerfile for building in Docker

cmd/freno/main.go
This PR adds a `-version` flag for printing the Freno version:
```
$ freno -version
freno version 1.0.5, git commit 48a765a4d63924a835269665cded456679e357a6
```
Also, the git commit is added to [the `starting freno` log line](https://github.com/github/freno/compare/add-version-flag?expand=1#diff-d89c1853247e7fc229e2585a95a5271fR75)
=> Add -version flag, print version

cmd/freno/main.go, pkg/config/config.go, pkg/http/api.go, pkg/http/api_test.go
This PR allows Freno to expose the [`net/http/pprof`](https://golang.org/pkg/net/http/pprof/) HTTP API for profiling Golang applications
This is an optional feature enabled by `-enable-profiling` or `EnableProfiling: true` in the config file
This allows `go tool pprof` to be used against Freno, example:
```
tim@Tims-MacBook-Pro freno % go tool pprof 'http://localhost:8088/debug/pprof/profile?seconds=10'
Fetching profile over HTTP from http://localhost:8088/debug/pprof/profile?seconds=10
Saved profile in /Users/tim/pprof/pprof.samples.cpu.003.pb.gz
Type: cpu
Time: Aug 18, 2020 at 9:23pm (CEST)
Duration: 10s, Total samples = 130ms ( 1.30%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 130ms, 100% of 130ms total
Showing top …
```
=> Allow pprof profiling HTTP API

.goreleaser.yml
This resolves a warning for a missing `maintainer` on package-install of v1.0.5
Merging straight to master as there is no logic change here 👍
=> Add 'maintainter' to .goreleaser.yml to fix install warning

.goreleaser.yml
This PR adds release name template for release builds and creates amd64-based binaries only
=> Add release name template to goreleaser, build amd64 only

.github/workflows/release.yml, .travis.yml, Dockerfile, Dockerfile.test, go.mod, script/bootstrap, script/build-deploy-tarball
This PR updates the build/test steps to use Golang 1.15
The docker image `golang:1.15-buster` uses a new Debian release so this PR makes a copy of `buster`->`stretch`. The `jessie` tarball was removed because it is EOL
=> Golang 1.15

internal/raft/file_snapshot.go, script/bootstrap
`os.ReadDir` is a more efficient than `ioutil.ReadDir` as stated here https://pkg.go.dev/io/ioutil#ReadDir. Since we are only using `IsDir()` and `Name()` in `getSnapshots`, we don't need to read the directory with full stat information using `ioutil.ReadDir`.
=> refactor: use `os.ReadDir` for lightweight directory reading

doc/http.md, pkg/http/api.go, pkg/throttle/check.go, pkg/throttle/throttler.go
When manually throttling an app, usually we want to throttle for only one cluster, not globally.
This adds `store_name` query parameter for `/throttle-app` endpoint to throttle app on specific store. On the backend it just uses `app/store` as key so no change to backend storage needed.
`/throttle-app/<app>`: throttle app globally
`/thottle-app/<app>?store_name=<cluster>`: throttle app on cluster
`/unthrottle-app/<app>`: unthrottle app globally and on all clusters
cc/ https://github.com/github/database-infrastructure/issues/4420
=> Throttle app by cluster

build.sh, doc/http.md, doc/mysql-backend.md, pkg/group/consensus_service.go, pkg/group/fsm.go, pkg/group/fsm_snapshot.go, pkg/group/mysql.go, pkg/group/store.go, pkg/http/api.go, pkg/throttle/throttler.go
adds GET endpoints from https://github.com/github/freno/issues/28 for skipping hosts dyanmically
`/skip-host/:hostName`
`/skip-host/:hostName/ttl/:ttlMinutes`
`/skipped-hosts`
`/recover-host/:hostName`
Implemented for raft and mysql backends. For MySQL backend it requires new table
```
CREATE TABLE skipped_hosts (
host_name varchar(128) NOT NULL,
skipped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
expires_at TIMESTAMP NOT NULL,
PRIMARY KEY (host_name)
);
```
closes #28
=> Skip hosts API

.goreleaser.yml
empty_folders is deprecated so goreleaser fails, see https://goreleaser.com/deprecations/#nfpmsempty_folders
=> Fix goreleaser empty_folders

.github/workflows/main.yml, .github/workflows/release.yml, internal/raft/net_transport.go, pkg/config/config.go, pkg/config/mysql_config.go, pkg/group/mysql.go, pkg/group/mysql_test.go, pkg/mysql/probe.go, pkg/mysql/probe_test.go, pkg/proxysql/client_test.go, script/bootstrap
This PR introduces two new settings:
- `ConfigurationSettings` -> `BackendCollation` - if specified, sets `collation=?` in the DSN for the backend MySQL database connection, replacing the default `charset=utf8mb4,utf8,latin1` setting
- `MySQLConfigurationSettings `->`Collation` - if specified, sets `collation=?` in the DSN for the monitored MySQL stores connections, replacing the default `charset=utf8mb4,utf8,latin1` setting
When these values are set to a charset that is common between MySQL 5.7 and 8.0 (e.g. `utf8mb4_unicode_520_ci`), this prevents Freno from breaking temporary replication from an 8.0 primary to a 5.7 replica.
This PR does not change the existing behaviour of Freno (i.e. setting `charset=utf8mb4,utf8,latin1`); instead it allows the existing behaviour to be overriden when …
=> Add collation settings to allow collation to override charset

script/build-deploy-tarball
Change build tarball to be able to deploy to `focal`
=> Add `focal` build

pkg/mysql/mysql_http_check.go, pkg/throttle/mysql.go, pkg/throttle/throttler.go
The `IgnoreHostsThreshold` in the cluster probe was not getting set to the value from the config when the cluster is using Vitess or ProxySQL.
This causes `IgnoreHostsCount` hosts to be ignored regardless of what the configured `IgnoreHostsThreshold` value is.
=> Set IgnoreHostsThreshold in ClusterProbe

doc/mysql-backend.md, pkg/group/mysql.go, pkg/throttle/throttler.go, vendor/github.com/patrickmn/go-cache/cache.go
Updates to change the default TTL behavior to never expire, per [this issue](https://github.com/github/database-infrastructure/issues/5627).
=> Add Permanent Throttle Option
